### ISSUE TITLE
use of the "selection" property throws type error

### ISSUE THREAD

**Issue by dtkirsch** [RSSchermer/ember-multiselect-checkboxes#14]
This is in conjunction with ember-cli 1.13.1 and ember-data 1.0.0-beta.16.1.  

This gives me a beautiful list of checkboxes:
`{{multiselect-checkboxes options=conditions labelProperty='displayName'}}`

... but when I add a property `selection=selectedConditions` as the readme tells me to, I get a TypeError thrown from the multiselect addon:
`    multiselect-checkboxes.js:8 Uncaught TypeError: Cannot read property 'contains' of undefined
    multiselect-checkboxes.js:8: return this.get('selection').contains(this.get('value'));`

**Comment by RSSchermer** [comment]
I think this may be because the `selectedConditions` you pass to the `selection` attribute might not be an Ember Array. 

Did you perhaps disable Ember's prototype extensions? Looking at the code now, that seems like it could be a reason for why this happens. That's definitely a bug, it should work without Ember's prototype extensions and I'll fix that.

If you didn't disable prototype extensions, then we'll have to keep digging. What kind of object is `selectedOptions`, where does it come from? Is it an Ember data `DS.ManyArray`?

**Comment by RSSchermer** [comment]
I just publish 0.4.4, which should eliminate the need to have prototype extensions enabled in a client application. 

Let me know if your problem persists or if this fixes your issue.

**Comment by dtkirsch** [comment]
Thanks Roland, yes all fixed now.
