### ISSUE TITLE
Disable automatic setting of the selection property

### ISSUE THREAD

**Issue by ForSpareParts** [RSSchermer/ember-multiselect-checkboxes#23]
Right now, while `{{multiselect-checkboxes}}` can expose an action (per #4), it also automatically updates the `selection` property on clicks. While this may be desirable in certain cases, it violates Ember's new "data down, actions up" paradigm. In an app that's primarily designed to use DDAU, this component stands out awkwardly.

I would propose adding an option to disable automatic updates of `selection`. If this option is `true`, actions would be fired, but without updating `selection` (leaving updating up to whomever handles the action). If it's `false`, the current behavior would be preserved. Does this seem reasonable?

**Comment by RSSchermer** [comment]
I empathize, but I don't want to rush into this. 

It seems ideally the `mut` helper should be used to signal the intent of mutability. The following would update the bound selection:

```hbs
<multiselect-checkboxes 
    options={{users}} 
    labelProperty='name' 
    selection={{mut selectedUsers}} />
```

This would not update the selection and trigger an action receiving a new selection object when a checkbox is checked:

```hbs
<multiselect-checkboxes 
    options={{users}} 
    labelProperty='name' 
    selection={{selectedUsers}} 
    onChange={{action 'selectionChanged'}} />
```

This however needs some care, especially with form inputs, which I consider this component to be analogous to. 

On the one hand, I feel as though the displayed checkboxes should always accurately reflect the value bound to the `selection` attribute. This however leads to the slightly odd situation where a user attempts to check a checkbox but seemingly nothing happens if the action bound to the `onChange` attribute neglects to update the value bound to the `selection` attribute. In a way, this forces the consumer to include logic in the bound action for always updating the value bound to the `selection` attribute.

On the other hand, the value bound to the `selection` attribute could be used only as the initial value and from then on the component maintains a hidden internal selection that it updates as checkboxes get checked or unchecked. Now however the displayed checkboxes no longer necessarily accurately reflect the value bound to the `selection` attribute.

Ember's DDAU story around form inputs feels not quite crystallized. Until now I was kind of hoping to follow a 'wait and see' strategy until Ember starts to really enforce DDAU and updates the behavior of its own input helpers so this component can conform to that behavior. I do however welcome any insight; perhaps there is some obvious line of reasoning for the proper choice.

**Comment by ForSpareParts** [comment]
I agree that there's a bit of awkwardness around inputs w/r/t DDAU.

For whatever it's worth, the behavior I'd expect is the one where nothing happens if `onchange` doesn't update `selection` (this is also what `ember-power-select` does, for instance). As far as giving the consumer the burden of calling the update behavior: that's the *intention* of the pattern, IMO. And now I'm giving a little more thought to why that is...

I think it comes down to a concept of "ownership." In the case where the rendering context owns the data powering the multiselect, the current behavior of this component is 100% idiomatic, i.e., "This is my data, I can change it if I want to." If the data came from *above* the current rendering context, then requiring an action to change it is more idiomatic -- it's somebody else's data, and if I want it changed, I have to ask them to do it.

Of course, only the former scenario is natively supported by Ember at present. Perhaps it would make sense to incorporate [ember-one-way-controls](https://github.com/dockyard/ember-one-way-controls) into this project? I used it to add one-way-binding style input controls to my app for another purpose, and it worked pretty well. It doesn't "block" the input (the DOM updates no matter what) but other than that it was pretty straightforward.

**Comment by RSSchermer** [comment]
I don't think it will be necessary to incorporate ember-one-way-controls into this project. It should be fine for the component to use mutability internally, regardless of the direction chosen, as long as it does not mutate the values bound to its attributes if they are not marked with `mut`. If you want to use a custom template block, you should be able to use ember-one-way-controls just fine.

I will implement this (probably over the weekend), but I will do so on a separate branch that I will probably not merge into master for the time being. This should provide you with a shortterm fix for this issue (by pointing your `package.json` to this specific branch) while still allowing me a bit more time to wait and see before a definitive merge into master, as I would rather not have to break BC more than once over this.

**Comment by ForSpareParts** [comment]
OK. Thanks for your help!

**Comment by RSSchermer** [comment]
I realized when implementing this that my initial inclination to use `mut` to signal the intent of mutating the  value bound to the `selection` attribute was stretching the semantics of `mut` somewhat and was probably not appropriate. On reflection, your suggested approach of adding an additional attribute to control this behavior indeed seemed to be the better approach. As a bonus, this also allowed for a backwards compatible implementation and thus I did merge it into master, see [the change log for 0.7.0](https://github.com/RSSchermer/ember-multiselect-checkboxes/blob/0.7.0/CHANGELOG.md).

I'll close this for now, but I'd be happy to reopen if this is not working quite as you hoped/expected.
