### ISSUE TITLE
Selection becomes empty after trying to check all items programmatically.

### ISSUE THREAD

**Issue by anikolaev** [RSSchermer/ember-multiselect-checkboxes#3]
I try to add link which will check all checkboxes. For Persons example from the Demo I added to controller:
```
  actions: {
      selectAll: function() {
        var items = this.get('persons').filter(function() {
            return true;
        });
        this.set("selectedPersons", items);
      }
  }
```

In template:
```
  <a {{action "selectAll"}}>Select all</a>
```
I see all checkboxes checked but selectedPersons array is empty. It seems that component only correctly processes manual checking / unchecking of checkboxes. 

Clearing checkboxes with:
```
this.set("selectedPersons", []);
```
also works incorrectly.

Added JSBin: http://emberjs.jsbin.com/jofekefaze

**Comment by RSSchermer** [comment]
Thanks a lot for making the JSBin, that's very helpful :thumbsup: 

This is indeed very strange behaviour. I will look into it over the weekend.

**Comment by anikolaev** [comment]
It seems it can be fixed with removing isSelectedChanged() and changing isSelected() this way:

```javascript
isSelected: function (key, check) {
    // setter
    if (arguments.length > 1) {
      var selected = this.get('selection').contains(this.get('value'));
      if (check && !selected) {
        this.get('selection').addObject(this.get('value'));
      } else if (!check && selected) {
        this.get('selection').removeObject(this.get('value'));
      }
    }
    
    // getter
    return this.get('selection').contains(this.get('value'));
  }.property('value', 'selection'),
```

See http://jsbin.com/niqulonufo

**Comment by RSSchermer** [comment]
Thanks for digging into this some more, that's a very nice fix. A just published an updated version, let me know if everything works properly for you now. As an aside, the following also seems to work for `selectAll`:
```js
selectAllPersons: function() {
  this.set("selectedPersons", this.get('persons').copy());
}
```

**Comment by anikolaev** [comment]
Yes, it works fine.

**Comment by jeffrey008** [comment]
@RSSchermer this addon is just still awesome after 2 years. Could u explain why 
`this.set("selectedPersons", this.get('persons').copy());` works? Thanks!

**Comment by RSSchermer** [comment]
Hi @jeffrey008,

For "select all" functionality, you essentially want to set you `selection` property to a collection that contains the same values as the collection bound to your `options` property. This can't be the exact same collection instance though, because then weird things would happen; if we for example would try to remove an element from the `selection` collection (by e.g. unchecking the element), then because the `options` collection is the exact same instance, the option would also disappear. So instead we make a copy of the `options` collection, which gives us a new collection instance we can bind to `selection` so that the selection can then be changed independently of the options.

**Comment by jeffrey008** [comment]
@RSSchermer wow tanks for the nice explanation! Maybe I will make one demo for "select all/unselect all" in some time later :)
